In [2]:
import numpy as np
arr = np.arange(15).reshape(3,5)

In [3]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
arr.shape

(3, 5)

In [6]:
a.ndim

NameError: name 'a' is not defined

In [7]:
arr.dmin

AttributeError: 'numpy.ndarray' object has no attribute 'dmin'

In [8]:
arr.ndim

2

In [9]:
arr.dtype.name

'int64'

In [10]:
arr.size

15

In [11]:
type(arr)

numpy.ndarray

In [12]:
floatArr = np.array([1.2, 25])
floatArr.dtype

dtype('float64')

In [13]:
cmplxArr = np.array([[1,3],[3,4]], dtype='complex')
cmplxArr

array([[1.+0.j, 3.+0.j],
       [3.+0.j, 4.+0.j]])

In [14]:
np.zeroes((3,4))

AttributeError: module 'numpy' has no attribute 'zeroes'

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.empty((2,3))

array([[1.1805829e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [17]:
# how to get floats
from numpy import pi
x = np.linspace(0, 2*pi, 100)

In [18]:
f = np.sin(x)

In [19]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [20]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [22]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [26]:
b = np.arange(132).reshape(12,11)
print(b)

[[  0   1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20  21]
 [ 22  23  24  25  26  27  28  29  30  31  32]
 [ 33  34  35  36  37  38  39  40  41  42  43]
 [ 44  45  46  47  48  49  50  51  52  53  54]
 [ 55  56  57  58  59  60  61  62  63  64  65]
 [ 66  67  68  69  70  71  72  73  74  75  76]
 [ 77  78  79  80  81  82  83  84  85  86  87]
 [ 88  89  90  91  92  93  94  95  96  97  98]
 [ 99 100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130 131]]


In [27]:
print(np.arange(1000000))

[     0      1      2 ... 999997 999998 999999]


In [28]:
arr = np.arange(5)
arrb = np.array([10,20,30,40,50])
arr-arrb

array([-10, -19, -28, -37, -46])

In [30]:
arr

array([0, 1, 2, 3, 4])

In [32]:
arr @ arrb

400

In [33]:
arr.min()

0

In [34]:
arr.max()

4

In [35]:
arr.sum()

10

In [37]:
arr = np.array([[[0,1,2],
                [10,12,13],
                [100,101,102],
                [110,112,113]]])
arr.shape()

TypeError: 'tuple' object is not callable

In [38]:
np.shape

<function numpy.shape(a)>

In [39]:
arr.shape

(1, 4, 3)

In [40]:
c[1,...]

NameError: name 'c' is not defined

In [41]:
arr[1,...]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [42]:
arr[0,...]

array([[  0,   1,   2],
       [ 10,  12,  13],
       [100, 101, 102],
       [110, 112, 113]])

In [43]:
for element in arr.flat:
    print(element)

0
1
2
10
12
13
100
101
102
110
112
113


In [44]:
a = np.floor(10*np.random.random((3,5)))
a

array([[3., 0., 3., 6., 5.],
       [5., 0., 3., 2., 1.],
       [2., 2., 8., 1., 9.]])

In [45]:
a.shape

(3, 5)

In [46]:
a.flat

In [47]:
a.ravel()

array([3., 0., 3., 6., 5., 5., 0., 3., 2., 1., 2., 2., 8., 1., 9.])

In [48]:
list(a.ravel())

[3.0, 0.0, 3.0, 6.0, 5.0, 5.0, 0.0, 3.0, 2.0, 1.0, 2.0, 2.0, 8.0, 1.0, 9.0]

In [49]:
a.T

array([[3., 5., 2.],
       [0., 0., 2.],
       [3., 3., 8.],
       [6., 2., 1.],
       [5., 1., 9.]])

In [50]:
a.reshape(15,1)

array([[3.],
       [0.],
       [3.],
       [6.],
       [5.],
       [5.],
       [0.],
       [3.],
       [2.],
       [1.],
       [2.],
       [2.],
       [8.],
       [1.],
       [9.]])

In [51]:
arr = np.floor(10*np.random.random((2,2)))
arrb = np.floor(10*np.random.random((2,2)))
np.vstack(arr, arrb)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [52]:
np.vstack((arr,arrb))

array([[8., 4.],
       [3., 7.],
       [0., 0.],
       [5., 7.]])

In [53]:
np.hstack((arr,arrb))

array([[8., 4., 0., 0.],
       [3., 7., 5., 7.]])

In [54]:
np.hsplit(arr,1)

[array([[8., 4.],
        [3., 7.]])]

In [55]:
np.hsplit(arr,2)

[array([[8.],
        [3.]]), array([[4.],
        [7.]])]